use `fabapp-v0.9`;

DROP TABLE IF EXISTS SHEET_INVENTORY;
DROP TABLE IF EXISTS SHEETS;
DROP TABLE IF EXISTS VARIANTS;
DROP TABLE IF EXISTS CUT_SIZES;

DROP TABLE IF EXISTS sheet_inventory;
DROP TABLE IF EXISTS sheet_type;
DROP TABLE IF EXISTS variants;
DROP TABLE IF EXISTS cut_sizes;
DROP TABLE IF EXISTS cutsize_children;

